steps:
  - label: ":white_tick: Success annotation"
    commands:
      - yarn install
      - yarn test-success

  - label: ":x: Failure annotation"
    commands:
      - yarn install
      - yarn test-failure
    soft_fail:
      - exit_status: 1

  - label: ":x: Build, no tests"
    commands:
      - yarn install
      - yarn test-no-tests
    soft_fail:
      - exit_status: 1
    
  - label: ":tick: Build, no tests but ok"
    commands:
      - yarn install
      - yarn test-no-tests-but-ok
    