name: Build & Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [14.x, 16.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    
    - run: yarn install
    - run: yarn build
    - run: yarn pack
    # - name: Upload artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     path: '*.tgz'

    - name: Semantic Release
      # Run semantic-release in "dry run" on branches
      if: github.ref != 'refs/heads/main'
      uses: cycjimmy/semantic-release-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        dry_run: true

    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: ${{ matrix.node-version }}
    # - run: yarn install
    # - run: yarn build
    # - run: yarn pack
    # - name: Upload artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     path: '*.tgz'
